/**
 * Plan — a DAG of steps that solves a task.
 * Generated by the Planner, editable before execution.
 */

import type { Agent } from './agent.js'
import type { BudgetEstimate, CostEvent } from './budget.js'
import type { Task } from './task.js'

export type PlanStatus = 'draft' | 'approved' | 'running' | 'complete' | 'failed'

export interface StepCascadeConfig {
  enabled: boolean
  /** Quality threshold 0-1. Below this, escalate to next model. */
  threshold: number
  /** Allow escalation across provider boundaries. */
  crossProvider: boolean
  /** Max models to try per step before accepting best result. */
  maxEscalations: number
}

export interface CascadeTraceEntry {
  model: string
  provider: string
  tier: string
  costCents: number
  qualityScore: number
  accepted: boolean
  durationMs: number
}
export type StepStatus = 'pending' | 'running' | 'complete' | 'skipped' | 'failed'
export type ExecutionMode = 'deep' | 'swarm'

export interface Plan {
  id: string
  task: Task
  steps: Step[]
  mode: ExecutionMode
  estimatedCost: BudgetEstimate
  status: PlanStatus
}

export interface Step {
  id: string
  agent: Agent | AgentRef
  input: StepInput
  dependencies: string[]
  retries?: number
  timeoutMs?: number
  optional?: boolean
  /** Approval gate — pauses execution until approved */
  gate?: ApprovalGate
  status: StepStatus
  output?: unknown
  cost?: CostEvent
  error?: string
  /** Set when cascade routing was used for this step. */
  cascadeConfig?: StepCascadeConfig
  cascadeTrace?: CascadeTraceEntry[]
}

export interface ApprovalGate {
  type: 'approval'
  message: string
  /** Timeout before auto-rejecting. Default: no timeout. */
  timeoutMs?: number
}

export type ApprovalCallback = (gate: ApprovalGate & { stepId: string; agentName: string }) => Promise<'approved' | 'rejected'>

export interface AgentRef {
  name: string
  capabilities?: string[]
}

export type StepInput =
  | { type: 'literal'; value: unknown }
  | { type: 'task_input' }
  | { type: 'step_output'; stepId: string; path?: string }
  | { type: 'merged'; sources: StepInput[] }

export function isAgentRef(v: unknown): v is AgentRef {
  return typeof v === 'object' && v !== null && 'name' in v && !('execute' in v)
}
